INSERT INTO TCity (cZipCode,cName) VALUES ('0555','Scanning');
INSERT INTO TCity (cZipCode,cName) VALUES ('0783','Facility');
INSERT INTO TCity (cZipCode,cName) VALUES ('0800','H¯je Taastrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('0877','K¯benhavn C');
INSERT INTO TCity (cZipCode,cName) VALUES ('0892','SjÊlland USF P');
INSERT INTO TCity (cZipCode,cName) VALUES ('0893','SjÊlland USF B');
INSERT INTO TCity (cZipCode,cName) VALUES ('0894','Udbetaling');
INSERT INTO TCity (cZipCode,cName) VALUES ('0899','Kommuneservice');
INSERT INTO TCity (cZipCode,cName) VALUES ('0900','K¯benhavn C');
INSERT INTO TCity (cZipCode,cName) VALUES ('0910','K¯benhavn C');
INSERT INTO TCity (cZipCode,cName) VALUES ('0913','K¯benhavns Pakkecenter');
INSERT INTO TCity (cZipCode,cName) VALUES ('0914','K¯benhavns Pakkecenter');
INSERT INTO TCity (cZipCode,cName) VALUES ('0917','K¯benhavns Pakkecenter');
INSERT INTO TCity (cZipCode,cName) VALUES ('0918','K¯benhavns Pakke BRC');
INSERT INTO TCity (cZipCode,cName) VALUES ('0919','Returprint BRC');
INSERT INTO TCity (cZipCode,cName) VALUES ('0929','K¯benhavn C');
INSERT INTO TCity (cZipCode,cName) VALUES ('0960','Internationalt Postcenter');
INSERT INTO TCity (cZipCode,cName) VALUES ('0999','K¯benhavn C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1001','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1002','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1003','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1004','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1005','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1006','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1007','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1008','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1009','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1010','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1011','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1012','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1013','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1014','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1015','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1016','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1017','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1018','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1019','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1020','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1021','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1022','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1023','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1024','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1025','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1026','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1045','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1050','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1051','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1052','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1053','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1054','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1055','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1055','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1056','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1057','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1058','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1059','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1060','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1061','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1062','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1063','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1064','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1065','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1066','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1067','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1068','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1069','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1070','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1071','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1072','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1073','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1074','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1092','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1093','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1095','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1098','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1100','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1101','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1102','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1103','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1104','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1105','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1106','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1107','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1110','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1111','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1112','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1113','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1114','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1115','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1116','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1117','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1118','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1119','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1120','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1121','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1122','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1123','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1124','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1125','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1126','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1127','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1128','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1129','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1130','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1131','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1140','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1147','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1148','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1150','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1151','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1152','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1153','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1154','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1155','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1156','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1157','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1158','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1159','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1160','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1161','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1162','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1164','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1165','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1165','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1166','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1167','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1168','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1169','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1170','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1171','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1172','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1173','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1174','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1175','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1200','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1201','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1202','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1203','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1204','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1205','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1206','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1207','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1208','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1209','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1210','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1211','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1212','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1213','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1214','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1215','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1216','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1217','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1218','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1218','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1218','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1218','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1218','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1218','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1219','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1220','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1221','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1240','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1250','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1251','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1252','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1253','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1254','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1255','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1256','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1257','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1259','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1259','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1260','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1261','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1263','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1263','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1264','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1265','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1266','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1267','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1268','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1270','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1271','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1300','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1301','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1302','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1303','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1304','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1306','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1307','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1307','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1308','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1309','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1310','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1311','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1312','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1313','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1314','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1315','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1316','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1317','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1318','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1319','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1320','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1321','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1322','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1323','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1324','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1325','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1326','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1327','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1328','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1329','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1350','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1352','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1353','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1354','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1355','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1356','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1357','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1358','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1359','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1359','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1360','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1361','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1361','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1362','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1363','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1364','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1365','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1366','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1367','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1368','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1369','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1370','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1371','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1400','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1400','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1401','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1402','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1402','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1402','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1402','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1402','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1403','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1406','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1407','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1408','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1409','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1410','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1411','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1411','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1412','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1413','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1414','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1415','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1416','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1417','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1418','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1419','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1420','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1421','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1422','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1423','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1424','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1425','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1426','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1427','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1428','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1429','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1430','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1432','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1432','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1432','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1433','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1433','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1433','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1433','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1433','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1433','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1433','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1434','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1434','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1435','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1436','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1436','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1436','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1436','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1436','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1436','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1437','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1438','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1438','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1438','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1438','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1438','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1439','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1440','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1441','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1441','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1441','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1448','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1450','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1451','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1452','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1453','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1454','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1455','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1456','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1457','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1458','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1459','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1460','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1461','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1462','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1463','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1464','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1465','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1466','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1467','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1468','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1470','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1471','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1472','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1473','K¯benhavn K');
INSERT INTO TCity (cZipCode,cName) VALUES ('1500','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1501','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1502','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1503','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1504','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1505','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1506','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1507','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1508','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1509','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1510','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1512','Returpost');
INSERT INTO TCity (cZipCode,cName) VALUES ('1513','Flytninger og Nejtak');
INSERT INTO TCity (cZipCode,cName) VALUES ('1532','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1533','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1550','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1550','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1551','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1552','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1553','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1553','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1554','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1555','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1556','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1557','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1558','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1559','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1560','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1561','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1561','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1562','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1563','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1564','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1567','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1568','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1569','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1570','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1570','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1571','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1572','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1573','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1574','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1575','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1576','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1577','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1577','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1577','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1592','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1599','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1600','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1601','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1602','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1603','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1604','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1605','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1606','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1607','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1608','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1609','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1610','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1611','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1612','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1613','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1614','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1615','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1616','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1617','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1618','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1619','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1620','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1620','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1621','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1622','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1623','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1624','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1630','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1631','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1632','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1633','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1634','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1635','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1650','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1651','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1652','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1653','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1654','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1655','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1656','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1657','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1658','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1659','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1660','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1660','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1661','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1662','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1663','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1664','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1665','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1666','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1667','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1668','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1669','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1670','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1671','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1671','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1672','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1673','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1674','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1675','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1676','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1677','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1699','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1700','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1701','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1702','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1703','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1704','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1705','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1706','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1707','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1708','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1709','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1710','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1711','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1711','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1712','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1714','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1715','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1716','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1717','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1718','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1719','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1720','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1721','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1722','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1723','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1724','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1725','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1726','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1727','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1728','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1729','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1730','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1731','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1732','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1733','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1734','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1735','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1736','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1737','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1738','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1739','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1749','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1750','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1751','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1752','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1753','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1754','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1755','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1756','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1757','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1758','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1759','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1760','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1761','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1762','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1763','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1764','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1765','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1766','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1770','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1771','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1772','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1773','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1774','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1775','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1777','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1780','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1782','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1785','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1786','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1787','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1790','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1799','K¯benhavn V');
INSERT INTO TCity (cZipCode,cName) VALUES ('1800','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1801','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1802','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1803','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1804','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1805','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1806','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1807','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1808','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1809','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1810','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1811','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1812','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1813','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1814','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1815','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1816','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1817','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1818','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1819','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1820','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1822','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1823','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1824','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1825','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1826','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1827','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1828','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1829','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1835','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1850','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1851','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1852','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1853','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1854','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1855','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1856','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1857','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1860','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1861','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1862','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1863','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1864','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1865','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1866','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1867','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1868','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1870','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1871','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1872','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1873','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1874','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1875','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1876','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1877','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1878','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1879','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1900','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1901','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1902','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1903','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1904','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1905','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1906','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1908','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1909','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1910','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1911','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1912','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1913','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1914','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1915','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1916','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1917','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1920','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1921','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1922','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1923','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1924','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1925','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1926','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1927','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1928','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1931','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1950','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1951','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1952','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1953','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1954','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1955','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1956','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1957','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1958','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1959','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1960','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1961','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1962','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1963','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1964','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1965','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1966','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1967','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1970','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1971','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1972','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1973','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('1974','Frederiksberg C');
INSERT INTO TCity (cZipCode,cName) VALUES ('2000','Frederiksberg');
INSERT INTO TCity (cZipCode,cName) VALUES ('2100','K¯benhavn ÿ');
INSERT INTO TCity (cZipCode,cName) VALUES ('2150','Nordhavn');
INSERT INTO TCity (cZipCode,cName) VALUES ('2200','K¯benhavn N');
INSERT INTO TCity (cZipCode,cName) VALUES ('2300','K¯benhavn S');
INSERT INTO TCity (cZipCode,cName) VALUES ('2400','K¯benhavn NV');
INSERT INTO TCity (cZipCode,cName) VALUES ('2412','Gr¯nland');
INSERT INTO TCity (cZipCode,cName) VALUES ('2450','K¯benhavn SV');
INSERT INTO TCity (cZipCode,cName) VALUES ('2500','Valby');
INSERT INTO TCity (cZipCode,cName) VALUES ('2600','Glostrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('2605','Br¯ndby');
INSERT INTO TCity (cZipCode,cName) VALUES ('2610','R¯dovre');
INSERT INTO TCity (cZipCode,cName) VALUES ('2620','Albertslund');
INSERT INTO TCity (cZipCode,cName) VALUES ('2625','VallensbÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('2630','Taastrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('2635','Ish¯j');
INSERT INTO TCity (cZipCode,cName) VALUES ('2640','Hedehusene');
INSERT INTO TCity (cZipCode,cName) VALUES ('2650','Hvidovre');
INSERT INTO TCity (cZipCode,cName) VALUES ('2660','Br¯ndby Strand');
INSERT INTO TCity (cZipCode,cName) VALUES ('2665','VallensbÊk Strand');
INSERT INTO TCity (cZipCode,cName) VALUES ('2670','Greve');
INSERT INTO TCity (cZipCode,cName) VALUES ('2680','Solr¯d Strand');
INSERT INTO TCity (cZipCode,cName) VALUES ('2690','Karlslunde');
INSERT INTO TCity (cZipCode,cName) VALUES ('2700','Br¯nsh¯j');
INSERT INTO TCity (cZipCode,cName) VALUES ('2720','Vanl¯se');
INSERT INTO TCity (cZipCode,cName) VALUES ('2730','Herlev');
INSERT INTO TCity (cZipCode,cName) VALUES ('2740','Skovlunde');
INSERT INTO TCity (cZipCode,cName) VALUES ('2750','Ballerup');
INSERT INTO TCity (cZipCode,cName) VALUES ('2760','MÂl¯v');
INSERT INTO TCity (cZipCode,cName) VALUES ('2765','Sm¯rum');
INSERT INTO TCity (cZipCode,cName) VALUES ('2770','Kastrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('2791','Drag¯r');
INSERT INTO TCity (cZipCode,cName) VALUES ('2800','Kongens Lyngby');
INSERT INTO TCity (cZipCode,cName) VALUES ('2820','Gentofte');
INSERT INTO TCity (cZipCode,cName) VALUES ('2830','Virum');
INSERT INTO TCity (cZipCode,cName) VALUES ('2840','Holte');
INSERT INTO TCity (cZipCode,cName) VALUES ('2850','NÊrum');
INSERT INTO TCity (cZipCode,cName) VALUES ('2860','S¯borg');
INSERT INTO TCity (cZipCode,cName) VALUES ('2870','DyssegÂrd');
INSERT INTO TCity (cZipCode,cName) VALUES ('2880','BagsvÊrd');
INSERT INTO TCity (cZipCode,cName) VALUES ('2900','Hellerup');
INSERT INTO TCity (cZipCode,cName) VALUES ('2920','Charlottenlund');
INSERT INTO TCity (cZipCode,cName) VALUES ('2930','Klampenborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('2942','Skodsborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('2950','VedbÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('2960','Rungsted Kyst');
INSERT INTO TCity (cZipCode,cName) VALUES ('2970','H¯rsholm');
INSERT INTO TCity (cZipCode,cName) VALUES ('2980','Kokkedal');
INSERT INTO TCity (cZipCode,cName) VALUES ('2990','NivÂ');
INSERT INTO TCity (cZipCode,cName) VALUES ('3000','Helsing¯r');
INSERT INTO TCity (cZipCode,cName) VALUES ('3050','HumlebÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('3060','EspergÊrde');
INSERT INTO TCity (cZipCode,cName) VALUES ('3070','Snekkersten');
INSERT INTO TCity (cZipCode,cName) VALUES ('3080','Tik¯b');
INSERT INTO TCity (cZipCode,cName) VALUES ('3100','HornbÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('3120','Dronningm¯lle');
INSERT INTO TCity (cZipCode,cName) VALUES ('3140','ÅlsgÂrde');
INSERT INTO TCity (cZipCode,cName) VALUES ('3150','HellebÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('3200','Helsinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('3210','Vejby');
INSERT INTO TCity (cZipCode,cName) VALUES ('3220','Tisvildeleje');
INSERT INTO TCity (cZipCode,cName) VALUES ('3230','GrÊsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('3250','Gilleleje');
INSERT INTO TCity (cZipCode,cName) VALUES ('3300','FrederiksvÊrk');
INSERT INTO TCity (cZipCode,cName) VALUES ('3310','ÿlsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('3320','SkÊvinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('3330','G¯rl¯se');
INSERT INTO TCity (cZipCode,cName) VALUES ('3360','Liseleje');
INSERT INTO TCity (cZipCode,cName) VALUES ('3370','Melby');
INSERT INTO TCity (cZipCode,cName) VALUES ('3390','Hundested');
INSERT INTO TCity (cZipCode,cName) VALUES ('3400','Hiller¯d');
INSERT INTO TCity (cZipCode,cName) VALUES ('3450','Aller¯d');
INSERT INTO TCity (cZipCode,cName) VALUES ('3460','Birker¯d');
INSERT INTO TCity (cZipCode,cName) VALUES ('3480','Fredensborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('3490','KvistgÂrd');
INSERT INTO TCity (cZipCode,cName) VALUES ('3500','VÊrl¯se');
INSERT INTO TCity (cZipCode,cName) VALUES ('3520','Farum');
INSERT INTO TCity (cZipCode,cName) VALUES ('3540','Lynge');
INSERT INTO TCity (cZipCode,cName) VALUES ('3550','Slangerup');
INSERT INTO TCity (cZipCode,cName) VALUES ('3600','Frederikssund');
INSERT INTO TCity (cZipCode,cName) VALUES ('3630','JÊgerspris');
INSERT INTO TCity (cZipCode,cName) VALUES ('3650','ÿlstykke');
INSERT INTO TCity (cZipCode,cName) VALUES ('3660','Stenl¯se');
INSERT INTO TCity (cZipCode,cName) VALUES ('3670','Veks¯ SjÊlland');
INSERT INTO TCity (cZipCode,cName) VALUES ('3700','R¯nne');
INSERT INTO TCity (cZipCode,cName) VALUES ('3720','Aakirkeby');
INSERT INTO TCity (cZipCode,cName) VALUES ('3730','Nex¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('3740','Svaneke');
INSERT INTO TCity (cZipCode,cName) VALUES ('3751','ÿstermarie');
INSERT INTO TCity (cZipCode,cName) VALUES ('3760','Gudhjem');
INSERT INTO TCity (cZipCode,cName) VALUES ('3770','Allinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('3782','Klemensker');
INSERT INTO TCity (cZipCode,cName) VALUES ('3790','Hasle');
INSERT INTO TCity (cZipCode,cName) VALUES ('4000','Roskilde');
INSERT INTO TCity (cZipCode,cName) VALUES ('4030','Tune');
INSERT INTO TCity (cZipCode,cName) VALUES ('4040','Jyllinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4050','Skibby');
INSERT INTO TCity (cZipCode,cName) VALUES ('4060','Kirke SÂby');
INSERT INTO TCity (cZipCode,cName) VALUES ('4070','Kirke Hyllinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4100','Ringsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('4129','Ringsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('4130','Viby SjÊlland');
INSERT INTO TCity (cZipCode,cName) VALUES ('4140','Borup');
INSERT INTO TCity (cZipCode,cName) VALUES ('4160','Herlufmagle');
INSERT INTO TCity (cZipCode,cName) VALUES ('4171','Glums¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4173','Fjenneslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('4174','Jystrup Midtsj');
INSERT INTO TCity (cZipCode,cName) VALUES ('4180','Sor¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4190','Munke Bjergby');
INSERT INTO TCity (cZipCode,cName) VALUES ('4200','Slagelse');
INSERT INTO TCity (cZipCode,cName) VALUES ('4220','Kors¯r');
INSERT INTO TCity (cZipCode,cName) VALUES ('4230','SkÊlsk¯r');
INSERT INTO TCity (cZipCode,cName) VALUES ('4241','Vemmelev');
INSERT INTO TCity (cZipCode,cName) VALUES ('4242','BÂslunde');
INSERT INTO TCity (cZipCode,cName) VALUES ('4243','Rude');
INSERT INTO TCity (cZipCode,cName) VALUES ('4244','Agers¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4245','Om¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4250','Fuglebjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('4261','Dalmose');
INSERT INTO TCity (cZipCode,cName) VALUES ('4262','Sandved');
INSERT INTO TCity (cZipCode,cName) VALUES ('4270','H¯ng');
INSERT INTO TCity (cZipCode,cName) VALUES ('4281','G¯rlev');
INSERT INTO TCity (cZipCode,cName) VALUES ('4291','Ruds Vedby');
INSERT INTO TCity (cZipCode,cName) VALUES ('4293','Dianalund');
INSERT INTO TCity (cZipCode,cName) VALUES ('4295','Stenlille');
INSERT INTO TCity (cZipCode,cName) VALUES ('4296','Nyrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('4300','HolbÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('4305','Or¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4320','Lejre');
INSERT INTO TCity (cZipCode,cName) VALUES ('4330','Hvals¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4340','T¯ll¯se');
INSERT INTO TCity (cZipCode,cName) VALUES ('4350','Ugerl¯se');
INSERT INTO TCity (cZipCode,cName) VALUES ('4360','Kirke Eskilstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('4370','Store Merl¯se');
INSERT INTO TCity (cZipCode,cName) VALUES ('4390','Vipper¯d');
INSERT INTO TCity (cZipCode,cName) VALUES ('4400','Kalundborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('4420','Regstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('4440','M¯rk¯v');
INSERT INTO TCity (cZipCode,cName) VALUES ('4450','Jyderup');
INSERT INTO TCity (cZipCode,cName) VALUES ('4460','Snertinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4470','Sveb¯lle');
INSERT INTO TCity (cZipCode,cName) VALUES ('4480','Store Fuglede');
INSERT INTO TCity (cZipCode,cName) VALUES ('4490','Jerslev SjÊlland');
INSERT INTO TCity (cZipCode,cName) VALUES ('4500','Nyk¯bing Sj');
INSERT INTO TCity (cZipCode,cName) VALUES ('4520','Svinninge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4532','Gislinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4534','H¯rve');
INSERT INTO TCity (cZipCode,cName) VALUES ('4540','FÂrevejle');
INSERT INTO TCity (cZipCode,cName) VALUES ('4550','AsnÊs');
INSERT INTO TCity (cZipCode,cName) VALUES ('4560','Vig');
INSERT INTO TCity (cZipCode,cName) VALUES ('4571','Grevinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4572','N¯rre Asmindrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('4573','H¯jby');
INSERT INTO TCity (cZipCode,cName) VALUES ('4581','R¯rvig');
INSERT INTO TCity (cZipCode,cName) VALUES ('4583','SjÊllands Odde');
INSERT INTO TCity (cZipCode,cName) VALUES ('4591','F¯llenslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('4592','Sejer¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4593','Eskebjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('4600','K¯ge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4621','Gadstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('4622','Havdrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('4623','Lille Skensved');
INSERT INTO TCity (cZipCode,cName) VALUES ('4632','BjÊverskov');
INSERT INTO TCity (cZipCode,cName) VALUES ('4640','Faxe');
INSERT INTO TCity (cZipCode,cName) VALUES ('4652','HÂrlev');
INSERT INTO TCity (cZipCode,cName) VALUES ('4653','Karise');
INSERT INTO TCity (cZipCode,cName) VALUES ('4654','Faxe Ladeplads');
INSERT INTO TCity (cZipCode,cName) VALUES ('4660','Store Heddinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4671','Str¯by');
INSERT INTO TCity (cZipCode,cName) VALUES ('4672','Klippinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4673','R¯dvig Stevns');
INSERT INTO TCity (cZipCode,cName) VALUES ('4681','Herf¯lge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4682','Tureby');
INSERT INTO TCity (cZipCode,cName) VALUES ('4683','R¯nnede');
INSERT INTO TCity (cZipCode,cName) VALUES ('4684','Holmegaard');
INSERT INTO TCity (cZipCode,cName) VALUES ('4690','Haslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('4700','NÊstved');
INSERT INTO TCity (cZipCode,cName) VALUES ('4720','PrÊst¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4733','Tappern¯je');
INSERT INTO TCity (cZipCode,cName) VALUES ('4735','Mern');
INSERT INTO TCity (cZipCode,cName) VALUES ('4736','KarrebÊksminde');
INSERT INTO TCity (cZipCode,cName) VALUES ('4750','Lundby');
INSERT INTO TCity (cZipCode,cName) VALUES ('4760','Vordingborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('4771','Kalvehave');
INSERT INTO TCity (cZipCode,cName) VALUES ('4772','LangebÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('4773','Stensved');
INSERT INTO TCity (cZipCode,cName) VALUES ('4780','Stege');
INSERT INTO TCity (cZipCode,cName) VALUES ('4791','Borre');
INSERT INTO TCity (cZipCode,cName) VALUES ('4792','Askeby');
INSERT INTO TCity (cZipCode,cName) VALUES ('4793','Bog¯ By');
INSERT INTO TCity (cZipCode,cName) VALUES ('4800','Nyk¯bing F');
INSERT INTO TCity (cZipCode,cName) VALUES ('4840','N¯rre Alslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('4850','Stubbek¯bing');
INSERT INTO TCity (cZipCode,cName) VALUES ('4862','Guldborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('4863','Eskilstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('4871','Horbelev');
INSERT INTO TCity (cZipCode,cName) VALUES ('4872','Idestrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('4873','VÊggerl¯se');
INSERT INTO TCity (cZipCode,cName) VALUES ('4874','Gedser');
INSERT INTO TCity (cZipCode,cName) VALUES ('4880','Nysted');
INSERT INTO TCity (cZipCode,cName) VALUES ('4891','Toreby L');
INSERT INTO TCity (cZipCode,cName) VALUES ('4892','Kettinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('4894','ÿster Ulslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('4895','Errindlev');
INSERT INTO TCity (cZipCode,cName) VALUES ('4900','Nakskov');
INSERT INTO TCity (cZipCode,cName) VALUES ('4912','Harpelunde');
INSERT INTO TCity (cZipCode,cName) VALUES ('4913','Horslunde');
INSERT INTO TCity (cZipCode,cName) VALUES ('4920','S¯llested');
INSERT INTO TCity (cZipCode,cName) VALUES ('4930','Maribo');
INSERT INTO TCity (cZipCode,cName) VALUES ('4941','Bandholm');
INSERT INTO TCity (cZipCode,cName) VALUES ('4942','Ask¯ og Lille¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4943','Torrig L');
INSERT INTO TCity (cZipCode,cName) VALUES ('4944','Fej¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4945','Fem¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('4951','N¯rreballe');
INSERT INTO TCity (cZipCode,cName) VALUES ('4952','Stokkemarke');
INSERT INTO TCity (cZipCode,cName) VALUES ('4953','Vesterborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('4960','Holeby');
INSERT INTO TCity (cZipCode,cName) VALUES ('4970','R¯dby');
INSERT INTO TCity (cZipCode,cName) VALUES ('4983','Dannemare');
INSERT INTO TCity (cZipCode,cName) VALUES ('4990','Saksk¯bing');
INSERT INTO TCity (cZipCode,cName) VALUES ('4992','MidtsjÊlland USF P');
INSERT INTO TCity (cZipCode,cName) VALUES ('5000','Odense C');
INSERT INTO TCity (cZipCode,cName) VALUES ('5029','Odense C');
INSERT INTO TCity (cZipCode,cName) VALUES ('5100','Odense C');
INSERT INTO TCity (cZipCode,cName) VALUES ('5200','Odense V');
INSERT INTO TCity (cZipCode,cName) VALUES ('5210','Odense NV');
INSERT INTO TCity (cZipCode,cName) VALUES ('5220','Odense Sÿ');
INSERT INTO TCity (cZipCode,cName) VALUES ('5230','Odense M');
INSERT INTO TCity (cZipCode,cName) VALUES ('5240','Odense Nÿ');
INSERT INTO TCity (cZipCode,cName) VALUES ('5250','Odense SV');
INSERT INTO TCity (cZipCode,cName) VALUES ('5260','Odense S');
INSERT INTO TCity (cZipCode,cName) VALUES ('5270','Odense N');
INSERT INTO TCity (cZipCode,cName) VALUES ('5290','Marslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('5300','Kerteminde');
INSERT INTO TCity (cZipCode,cName) VALUES ('5320','Agedrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5330','Munkebo');
INSERT INTO TCity (cZipCode,cName) VALUES ('5350','Rynkeby');
INSERT INTO TCity (cZipCode,cName) VALUES ('5370','Mesinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('5380','Dalby');
INSERT INTO TCity (cZipCode,cName) VALUES ('5390','Martofte');
INSERT INTO TCity (cZipCode,cName) VALUES ('5400','Bogense');
INSERT INTO TCity (cZipCode,cName) VALUES ('5450','Otterup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5462','Morud');
INSERT INTO TCity (cZipCode,cName) VALUES ('5463','Harndrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5464','Brenderup Fyn');
INSERT INTO TCity (cZipCode,cName) VALUES ('5466','Asperup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5471','S¯nders¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('5474','Veflinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('5485','Skamby');
INSERT INTO TCity (cZipCode,cName) VALUES ('5491','Blommenslyst');
INSERT INTO TCity (cZipCode,cName) VALUES ('5492','Vissenbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('5500','Middelfart');
INSERT INTO TCity (cZipCode,cName) VALUES ('5540','Ullerslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('5550','Langeskov');
INSERT INTO TCity (cZipCode,cName) VALUES ('5560','Aarup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5580','N¯rre Aaby');
INSERT INTO TCity (cZipCode,cName) VALUES ('5591','Gelsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('5592','Ejby');
INSERT INTO TCity (cZipCode,cName) VALUES ('5600','Faaborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('5601','Ly¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('5602','Avernak¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('5603','Bj¯rn¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('5610','Assens');
INSERT INTO TCity (cZipCode,cName) VALUES ('5620','Glamsbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('5631','Ebberup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5642','Millinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('5672','Broby');
INSERT INTO TCity (cZipCode,cName) VALUES ('5683','Haarby');
INSERT INTO TCity (cZipCode,cName) VALUES ('5690','Tommerup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5700','Svendborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('5750','Ringe');
INSERT INTO TCity (cZipCode,cName) VALUES ('5762','Vester Skerninge');
INSERT INTO TCity (cZipCode,cName) VALUES ('5771','Stenstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5772','KvÊrndrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5792','Årslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('5800','Nyborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('5853','ÿrbÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('5854','Gislev');
INSERT INTO TCity (cZipCode,cName) VALUES ('5856','Ryslinge');
INSERT INTO TCity (cZipCode,cName) VALUES ('5863','Ferritslev Fyn');
INSERT INTO TCity (cZipCode,cName) VALUES ('5871','Fr¯rup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5874','Hesselager');
INSERT INTO TCity (cZipCode,cName) VALUES ('5881','SkÂrup Fyn');
INSERT INTO TCity (cZipCode,cName) VALUES ('5882','Vejstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('5883','Oure');
INSERT INTO TCity (cZipCode,cName) VALUES ('5884','Gudme');
INSERT INTO TCity (cZipCode,cName) VALUES ('5892','Gudbjerg Sydfyn');
INSERT INTO TCity (cZipCode,cName) VALUES ('5900','Rudk¯bing');
INSERT INTO TCity (cZipCode,cName) VALUES ('5932','Humble');
INSERT INTO TCity (cZipCode,cName) VALUES ('5935','Bagenkop');
INSERT INTO TCity (cZipCode,cName) VALUES ('5943','Stryn¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('5953','TranekÊr');
INSERT INTO TCity (cZipCode,cName) VALUES ('5960','Marstal');
INSERT INTO TCity (cZipCode,cName) VALUES ('5965','Birkholm');
INSERT INTO TCity (cZipCode,cName) VALUES ('5970','∆r¯sk¯bing');
INSERT INTO TCity (cZipCode,cName) VALUES ('5985','S¯by ∆r¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('6000','Kolding');
INSERT INTO TCity (cZipCode,cName) VALUES ('6040','Egtved');
INSERT INTO TCity (cZipCode,cName) VALUES ('6051','Almind');
INSERT INTO TCity (cZipCode,cName) VALUES ('6052','Viuf');
INSERT INTO TCity (cZipCode,cName) VALUES ('6064','Jordrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('6070','Christiansfeld');
INSERT INTO TCity (cZipCode,cName) VALUES ('6091','Bjert');
INSERT INTO TCity (cZipCode,cName) VALUES ('6092','S¯nder Stenderup');
INSERT INTO TCity (cZipCode,cName) VALUES ('6093','Sj¯lund');
INSERT INTO TCity (cZipCode,cName) VALUES ('6094','Hejls');
INSERT INTO TCity (cZipCode,cName) VALUES ('6100','Haderslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('6200','Aabenraa');
INSERT INTO TCity (cZipCode,cName) VALUES ('6210','Bars¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('6230','R¯dekro');
INSERT INTO TCity (cZipCode,cName) VALUES ('6240','L¯gumkloster');
INSERT INTO TCity (cZipCode,cName) VALUES ('6261','Bredebro');
INSERT INTO TCity (cZipCode,cName) VALUES ('6270','T¯nder');
INSERT INTO TCity (cZipCode,cName) VALUES ('6280','H¯jer');
INSERT INTO TCity (cZipCode,cName) VALUES ('6300','GrÂsten');
INSERT INTO TCity (cZipCode,cName) VALUES ('6310','Broager');
INSERT INTO TCity (cZipCode,cName) VALUES ('6320','Egernsund');
INSERT INTO TCity (cZipCode,cName) VALUES ('6330','Padborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('6340','KrusÂ');
INSERT INTO TCity (cZipCode,cName) VALUES ('6360','Tinglev');
INSERT INTO TCity (cZipCode,cName) VALUES ('6372','Bylderup-Bov');
INSERT INTO TCity (cZipCode,cName) VALUES ('6392','Bolderslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('6400','S¯nderborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('6430','Nordborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('6440','Augustenborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('6470','Sydals');
INSERT INTO TCity (cZipCode,cName) VALUES ('6500','Vojens');
INSERT INTO TCity (cZipCode,cName) VALUES ('6510','Gram');
INSERT INTO TCity (cZipCode,cName) VALUES ('6520','Toftlund');
INSERT INTO TCity (cZipCode,cName) VALUES ('6534','Agerskov');
INSERT INTO TCity (cZipCode,cName) VALUES ('6535','Branderup J');
INSERT INTO TCity (cZipCode,cName) VALUES ('6541','Bevtoft');
INSERT INTO TCity (cZipCode,cName) VALUES ('6560','Sommersted');
INSERT INTO TCity (cZipCode,cName) VALUES ('6580','Vamdrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('6600','Vejen');
INSERT INTO TCity (cZipCode,cName) VALUES ('6621','Gesten');
INSERT INTO TCity (cZipCode,cName) VALUES ('6622','BÊkke');
INSERT INTO TCity (cZipCode,cName) VALUES ('6623','Vorbasse');
INSERT INTO TCity (cZipCode,cName) VALUES ('6630','R¯dding');
INSERT INTO TCity (cZipCode,cName) VALUES ('6640','Lunderskov');
INSERT INTO TCity (cZipCode,cName) VALUES ('6650','Br¯rup');
INSERT INTO TCity (cZipCode,cName) VALUES ('6660','Lintrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('6670','Holsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('6682','Hovborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('6683','F¯vling');
INSERT INTO TCity (cZipCode,cName) VALUES ('6690','G¯rding');
INSERT INTO TCity (cZipCode,cName) VALUES ('6700','Esbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('6701','Esbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('6705','Esbjerg ÿ');
INSERT INTO TCity (cZipCode,cName) VALUES ('6710','Esbjerg V');
INSERT INTO TCity (cZipCode,cName) VALUES ('6715','Esbjerg N');
INSERT INTO TCity (cZipCode,cName) VALUES ('6720','Fan¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('6731','TjÊreborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('6740','Bramming');
INSERT INTO TCity (cZipCode,cName) VALUES ('6752','Glejbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('6753','AgerbÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('6760','Ribe');
INSERT INTO TCity (cZipCode,cName) VALUES ('6771','Gredstedbro');
INSERT INTO TCity (cZipCode,cName) VALUES ('6780','SkÊrbÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('6792','R¯m¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('6800','Varde');
INSERT INTO TCity (cZipCode,cName) VALUES ('6818','≈Årre');
INSERT INTO TCity (cZipCode,cName) VALUES ('6823','Ansager');
INSERT INTO TCity (cZipCode,cName) VALUES ('6830','N¯rre Nebel');
INSERT INTO TCity (cZipCode,cName) VALUES ('6840','Oksb¯l');
INSERT INTO TCity (cZipCode,cName) VALUES ('6851','Janderup Vestj');
INSERT INTO TCity (cZipCode,cName) VALUES ('6852','Billum');
INSERT INTO TCity (cZipCode,cName) VALUES ('6853','Vejers Strand');
INSERT INTO TCity (cZipCode,cName) VALUES ('6854','Henne');
INSERT INTO TCity (cZipCode,cName) VALUES ('6855','Outrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('6857','BlÂvand');
INSERT INTO TCity (cZipCode,cName) VALUES ('6862','Tistrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('6870','ÿlgod');
INSERT INTO TCity (cZipCode,cName) VALUES ('6880','Tarm');
INSERT INTO TCity (cZipCode,cName) VALUES ('6893','Hemmet');
INSERT INTO TCity (cZipCode,cName) VALUES ('6900','Skjern');
INSERT INTO TCity (cZipCode,cName) VALUES ('6920','VidebÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('6933','KibÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('6940','Lem St');
INSERT INTO TCity (cZipCode,cName) VALUES ('6950','Ringk¯bing');
INSERT INTO TCity (cZipCode,cName) VALUES ('6960','Hvide Sande');
INSERT INTO TCity (cZipCode,cName) VALUES ('6971','Spjald');
INSERT INTO TCity (cZipCode,cName) VALUES ('6973','ÿrnh¯j');
INSERT INTO TCity (cZipCode,cName) VALUES ('6980','Tim');
INSERT INTO TCity (cZipCode,cName) VALUES ('6990','Ulfborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('7000','Fredericia');
INSERT INTO TCity (cZipCode,cName) VALUES ('7007','Fredericia');
INSERT INTO TCity (cZipCode,cName) VALUES ('7017','Taulov Pakkecenter');
INSERT INTO TCity (cZipCode,cName) VALUES ('7018','Pakker TLP');
INSERT INTO TCity (cZipCode,cName) VALUES ('7029','Fredericia');
INSERT INTO TCity (cZipCode,cName) VALUES ('7080','B¯rkop');
INSERT INTO TCity (cZipCode,cName) VALUES ('7100','Vejle');
INSERT INTO TCity (cZipCode,cName) VALUES ('7120','Vejle ÿst');
INSERT INTO TCity (cZipCode,cName) VALUES ('7130','Juelsminde');
INSERT INTO TCity (cZipCode,cName) VALUES ('7140','Stouby');
INSERT INTO TCity (cZipCode,cName) VALUES ('7150','Barrit');
INSERT INTO TCity (cZipCode,cName) VALUES ('7160','T¯rring');
INSERT INTO TCity (cZipCode,cName) VALUES ('7171','Uldum');
INSERT INTO TCity (cZipCode,cName) VALUES ('7173','Vonge');
INSERT INTO TCity (cZipCode,cName) VALUES ('7182','Bredsten');
INSERT INTO TCity (cZipCode,cName) VALUES ('7183','Randb¯l');
INSERT INTO TCity (cZipCode,cName) VALUES ('7184','Vandel');
INSERT INTO TCity (cZipCode,cName) VALUES ('7190','Billund');
INSERT INTO TCity (cZipCode,cName) VALUES ('7200','Grindsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('7250','Hejnsvig');
INSERT INTO TCity (cZipCode,cName) VALUES ('7260','S¯nder Omme');
INSERT INTO TCity (cZipCode,cName) VALUES ('7270','Stakroge');
INSERT INTO TCity (cZipCode,cName) VALUES ('7280','S¯nder Felding');
INSERT INTO TCity (cZipCode,cName) VALUES ('7300','Jelling');
INSERT INTO TCity (cZipCode,cName) VALUES ('7321','Gadbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('7323','Give');
INSERT INTO TCity (cZipCode,cName) VALUES ('7330','Brande');
INSERT INTO TCity (cZipCode,cName) VALUES ('7361','Ejstrupholm');
INSERT INTO TCity (cZipCode,cName) VALUES ('7362','Hampen');
INSERT INTO TCity (cZipCode,cName) VALUES ('7400','Herning');
INSERT INTO TCity (cZipCode,cName) VALUES ('7429','Herning');
INSERT INTO TCity (cZipCode,cName) VALUES ('7430','Ikast');
INSERT INTO TCity (cZipCode,cName) VALUES ('7441','Bording');
INSERT INTO TCity (cZipCode,cName) VALUES ('7442','Engesvang');
INSERT INTO TCity (cZipCode,cName) VALUES ('7451','Sunds');
INSERT INTO TCity (cZipCode,cName) VALUES ('7470','Karup J');
INSERT INTO TCity (cZipCode,cName) VALUES ('7480','Vildbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('7490','Aulum');
INSERT INTO TCity (cZipCode,cName) VALUES ('7500','Holstebro');
INSERT INTO TCity (cZipCode,cName) VALUES ('7540','Haderup');
INSERT INTO TCity (cZipCode,cName) VALUES ('7550','S¯rvad');
INSERT INTO TCity (cZipCode,cName) VALUES ('7560','Hjerm');
INSERT INTO TCity (cZipCode,cName) VALUES ('7570','Vemb');
INSERT INTO TCity (cZipCode,cName) VALUES ('7600','Struer');
INSERT INTO TCity (cZipCode,cName) VALUES ('7620','Lemvig');
INSERT INTO TCity (cZipCode,cName) VALUES ('7650','B¯vlingbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('7660','BÊkmarksbro');
INSERT INTO TCity (cZipCode,cName) VALUES ('7673','Harbo¯re');
INSERT INTO TCity (cZipCode,cName) VALUES ('7680','Thybor¯n');
INSERT INTO TCity (cZipCode,cName) VALUES ('7700','Thisted');
INSERT INTO TCity (cZipCode,cName) VALUES ('7730','Hanstholm');
INSERT INTO TCity (cZipCode,cName) VALUES ('7741','Fr¯strup');
INSERT INTO TCity (cZipCode,cName) VALUES ('7742','Vesl¯s');
INSERT INTO TCity (cZipCode,cName) VALUES ('7752','Snedsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('7755','Bedsted Thy');
INSERT INTO TCity (cZipCode,cName) VALUES ('7760','Hurup Thy');
INSERT INTO TCity (cZipCode,cName) VALUES ('7770','Vestervig');
INSERT INTO TCity (cZipCode,cName) VALUES ('7790','Thyholm');
INSERT INTO TCity (cZipCode,cName) VALUES ('7800','Skive');
INSERT INTO TCity (cZipCode,cName) VALUES ('7830','Vinderup');
INSERT INTO TCity (cZipCode,cName) VALUES ('7840','H¯jslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('7850','Stoholm Jyll');
INSERT INTO TCity (cZipCode,cName) VALUES ('7860','Sp¯ttrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('7870','Roslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('7884','Fur');
INSERT INTO TCity (cZipCode,cName) VALUES ('7900','Nyk¯bing M');
INSERT INTO TCity (cZipCode,cName) VALUES ('7950','Erslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('7960','Karby');
INSERT INTO TCity (cZipCode,cName) VALUES ('7970','Redsted M');
INSERT INTO TCity (cZipCode,cName) VALUES ('7980','Vils');
INSERT INTO TCity (cZipCode,cName) VALUES ('7990','ÿster Assels');
INSERT INTO TCity (cZipCode,cName) VALUES ('7992','Sydjylland/Fyn USF P');
INSERT INTO TCity (cZipCode,cName) VALUES ('7993','Sydjylland/Fyn USF B');
INSERT INTO TCity (cZipCode,cName) VALUES ('7996','Fakturaservice');
INSERT INTO TCity (cZipCode,cName) VALUES ('7997','Fakturascanning');
INSERT INTO TCity (cZipCode,cName) VALUES ('7998','Statsservice');
INSERT INTO TCity (cZipCode,cName) VALUES ('7999','Kommunepost');
INSERT INTO TCity (cZipCode,cName) VALUES ('8000','Aarhus C');
INSERT INTO TCity (cZipCode,cName) VALUES ('8100','Aarhus C');
INSERT INTO TCity (cZipCode,cName) VALUES ('8200','Aarhus N');
INSERT INTO TCity (cZipCode,cName) VALUES ('8210','Aarhus V');
INSERT INTO TCity (cZipCode,cName) VALUES ('8220','Brabrand');
INSERT INTO TCity (cZipCode,cName) VALUES ('8229','Risskov ÿ');
INSERT INTO TCity (cZipCode,cName) VALUES ('8230','Åbyh¯j');
INSERT INTO TCity (cZipCode,cName) VALUES ('8240','Risskov');
INSERT INTO TCity (cZipCode,cName) VALUES ('8245','Risskov ÿ');
INSERT INTO TCity (cZipCode,cName) VALUES ('8250','EgÂ');
INSERT INTO TCity (cZipCode,cName) VALUES ('8260','Viby J');
INSERT INTO TCity (cZipCode,cName) VALUES ('8270','H¯jbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('8300','Odder');
INSERT INTO TCity (cZipCode,cName) VALUES ('8305','Sams¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('8310','Tranbjerg J');
INSERT INTO TCity (cZipCode,cName) VALUES ('8320','MÂrslet');
INSERT INTO TCity (cZipCode,cName) VALUES ('8330','Beder');
INSERT INTO TCity (cZipCode,cName) VALUES ('8340','Malling');
INSERT INTO TCity (cZipCode,cName) VALUES ('8350','Hundslund');
INSERT INTO TCity (cZipCode,cName) VALUES ('8355','Solbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('8361','Hasselager');
INSERT INTO TCity (cZipCode,cName) VALUES ('8362','H¯rning');
INSERT INTO TCity (cZipCode,cName) VALUES ('8370','Hadsten');
INSERT INTO TCity (cZipCode,cName) VALUES ('8380','Trige');
INSERT INTO TCity (cZipCode,cName) VALUES ('8381','Tilst');
INSERT INTO TCity (cZipCode,cName) VALUES ('8382','Hinnerup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8400','Ebeltoft');
INSERT INTO TCity (cZipCode,cName) VALUES ('8410','R¯nde');
INSERT INTO TCity (cZipCode,cName) VALUES ('8420','Knebel');
INSERT INTO TCity (cZipCode,cName) VALUES ('8444','Balle');
INSERT INTO TCity (cZipCode,cName) VALUES ('8450','Hammel');
INSERT INTO TCity (cZipCode,cName) VALUES ('8462','Harlev J');
INSERT INTO TCity (cZipCode,cName) VALUES ('8464','Galten');
INSERT INTO TCity (cZipCode,cName) VALUES ('8471','Sabro');
INSERT INTO TCity (cZipCode,cName) VALUES ('8472','Sporup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8500','Grenaa');
INSERT INTO TCity (cZipCode,cName) VALUES ('8520','Lystrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8530','Hjortsh¯j');
INSERT INTO TCity (cZipCode,cName) VALUES ('8541','Sk¯dstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8543','Hornslet');
INSERT INTO TCity (cZipCode,cName) VALUES ('8544','M¯rke');
INSERT INTO TCity (cZipCode,cName) VALUES ('8550','RyomgÂrd');
INSERT INTO TCity (cZipCode,cName) VALUES ('8560','Kolind');
INSERT INTO TCity (cZipCode,cName) VALUES ('8570','Trustrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8581','Nimtofte');
INSERT INTO TCity (cZipCode,cName) VALUES ('8585','Glesborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('8586','ÿrum Djurs');
INSERT INTO TCity (cZipCode,cName) VALUES ('8592','Anholt');
INSERT INTO TCity (cZipCode,cName) VALUES ('8600','Silkeborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('8620','Kjellerup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8632','Lemming');
INSERT INTO TCity (cZipCode,cName) VALUES ('8641','Sorring');
INSERT INTO TCity (cZipCode,cName) VALUES ('8643','Ans By');
INSERT INTO TCity (cZipCode,cName) VALUES ('8653','Them');
INSERT INTO TCity (cZipCode,cName) VALUES ('8654','Bryrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8660','Skanderborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('8670','LÂsby');
INSERT INTO TCity (cZipCode,cName) VALUES ('8680','Ry');
INSERT INTO TCity (cZipCode,cName) VALUES ('8700','Horsens');
INSERT INTO TCity (cZipCode,cName) VALUES ('8721','DaugÂrd');
INSERT INTO TCity (cZipCode,cName) VALUES ('8722','Hedensted');
INSERT INTO TCity (cZipCode,cName) VALUES ('8723','L¯sning');
INSERT INTO TCity (cZipCode,cName) VALUES ('8732','HovedgÂrd');
INSERT INTO TCity (cZipCode,cName) VALUES ('8740','BrÊdstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8751','Gedved');
INSERT INTO TCity (cZipCode,cName) VALUES ('8752','ÿstbirk');
INSERT INTO TCity (cZipCode,cName) VALUES ('8762','Flemming');
INSERT INTO TCity (cZipCode,cName) VALUES ('8763','Rask M¯lle');
INSERT INTO TCity (cZipCode,cName) VALUES ('8765','Klovborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('8766','N¯rre Snede');
INSERT INTO TCity (cZipCode,cName) VALUES ('8781','Stenderup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8783','Hornsyld');
INSERT INTO TCity (cZipCode,cName) VALUES ('8789','Endelave');
INSERT INTO TCity (cZipCode,cName) VALUES ('8799','Tun¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('8800','Viborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('8830','Tjele');
INSERT INTO TCity (cZipCode,cName) VALUES ('8831','L¯gstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8832','Skals');
INSERT INTO TCity (cZipCode,cName) VALUES ('8840','R¯dkÊrsbro');
INSERT INTO TCity (cZipCode,cName) VALUES ('8850','Bjerringbro');
INSERT INTO TCity (cZipCode,cName) VALUES ('8860','Ulstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8870','LangÂ');
INSERT INTO TCity (cZipCode,cName) VALUES ('8881','Thors¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('8882','FÂrvang');
INSERT INTO TCity (cZipCode,cName) VALUES ('8883','Gjern');
INSERT INTO TCity (cZipCode,cName) VALUES ('8900','Randers C');
INSERT INTO TCity (cZipCode,cName) VALUES ('8920','Randers NV');
INSERT INTO TCity (cZipCode,cName) VALUES ('8930','Randers Nÿ');
INSERT INTO TCity (cZipCode,cName) VALUES ('8940','Randers SV');
INSERT INTO TCity (cZipCode,cName) VALUES ('8950','ÿrsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('8960','Randers Sÿ');
INSERT INTO TCity (cZipCode,cName) VALUES ('8961','AllingÂbro');
INSERT INTO TCity (cZipCode,cName) VALUES ('8963','Auning');
INSERT INTO TCity (cZipCode,cName) VALUES ('8970','Havndal');
INSERT INTO TCity (cZipCode,cName) VALUES ('8981','Spentrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('8983','Gjerlev J');
INSERT INTO TCity (cZipCode,cName) VALUES ('8990','FÂrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9000','Aalborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('9029','Aalborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('9100','Aalborg');
INSERT INTO TCity (cZipCode,cName) VALUES ('9200','Aalborg SV');
INSERT INTO TCity (cZipCode,cName) VALUES ('9210','Aalborg Sÿ');
INSERT INTO TCity (cZipCode,cName) VALUES ('9220','Aalborg ÿst');
INSERT INTO TCity (cZipCode,cName) VALUES ('9230','Svenstrup J');
INSERT INTO TCity (cZipCode,cName) VALUES ('9240','Nibe');
INSERT INTO TCity (cZipCode,cName) VALUES ('9260','Gistrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9270','Klarup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9280','Storvorde');
INSERT INTO TCity (cZipCode,cName) VALUES ('9293','Kongerslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('9300','SÊby');
INSERT INTO TCity (cZipCode,cName) VALUES ('9310','Vodskov');
INSERT INTO TCity (cZipCode,cName) VALUES ('9320','Hjallerup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9330','Dronninglund');
INSERT INTO TCity (cZipCode,cName) VALUES ('9340','Asaa');
INSERT INTO TCity (cZipCode,cName) VALUES ('9352','Dybvad');
INSERT INTO TCity (cZipCode,cName) VALUES ('9362','Gandrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9370','Hals');
INSERT INTO TCity (cZipCode,cName) VALUES ('9380','Vestbjerg');
INSERT INTO TCity (cZipCode,cName) VALUES ('9381','Sulsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('9382','Tylstrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9400','N¯rresundby');
INSERT INTO TCity (cZipCode,cName) VALUES ('9430','Vadum');
INSERT INTO TCity (cZipCode,cName) VALUES ('9440','Aabybro');
INSERT INTO TCity (cZipCode,cName) VALUES ('9460','Brovst');
INSERT INTO TCity (cZipCode,cName) VALUES ('9480','L¯kken');
INSERT INTO TCity (cZipCode,cName) VALUES ('9490','Pandrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9492','Blokhus');
INSERT INTO TCity (cZipCode,cName) VALUES ('9493','Saltum');
INSERT INTO TCity (cZipCode,cName) VALUES ('9500','Hobro');
INSERT INTO TCity (cZipCode,cName) VALUES ('9510','Arden');
INSERT INTO TCity (cZipCode,cName) VALUES ('9520','Sk¯rping');
INSERT INTO TCity (cZipCode,cName) VALUES ('9530','St¯vring');
INSERT INTO TCity (cZipCode,cName) VALUES ('9541','Suldrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9550','Mariager');
INSERT INTO TCity (cZipCode,cName) VALUES ('9560','Hadsund');
INSERT INTO TCity (cZipCode,cName) VALUES ('9574','BÊlum');
INSERT INTO TCity (cZipCode,cName) VALUES ('9575','Terndrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9600','Aars');
INSERT INTO TCity (cZipCode,cName) VALUES ('9610','N¯rager');
INSERT INTO TCity (cZipCode,cName) VALUES ('9620','Aalestrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9631','Gedsted');
INSERT INTO TCity (cZipCode,cName) VALUES ('9632','M¯ldrup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9640','Fars¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('9670','L¯gst¯r');
INSERT INTO TCity (cZipCode,cName) VALUES ('9681','Ranum');
INSERT INTO TCity (cZipCode,cName) VALUES ('9690','Fjerritslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('9700','Br¯nderslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('9740','Jerslev J');
INSERT INTO TCity (cZipCode,cName) VALUES ('9750','ÿstervrÂ');
INSERT INTO TCity (cZipCode,cName) VALUES ('9760','VrÂ');
INSERT INTO TCity (cZipCode,cName) VALUES ('9800','Hj¯rring');
INSERT INTO TCity (cZipCode,cName) VALUES ('9830','TÂrs');
INSERT INTO TCity (cZipCode,cName) VALUES ('9850','Hirtshals');
INSERT INTO TCity (cZipCode,cName) VALUES ('9870','Sindal');
INSERT INTO TCity (cZipCode,cName) VALUES ('9881','Bindslev');
INSERT INTO TCity (cZipCode,cName) VALUES ('9900','Frederikshavn');
INSERT INTO TCity (cZipCode,cName) VALUES ('9940','LÊs¯');
INSERT INTO TCity (cZipCode,cName) VALUES ('9970','Strandby');
INSERT INTO TCity (cZipCode,cName) VALUES ('9981','Jerup');
INSERT INTO TCity (cZipCode,cName) VALUES ('9982','≈lbÊk');
INSERT INTO TCity (cZipCode,cName) VALUES ('9990','Skagen');
INSERT INTO TCity (cZipCode,cName) VALUES ('9992','Jylland USF P');
INSERT INTO TCity (cZipCode,cName) VALUES ('9993','Jylland USF B');
INSERT INTO TCity (cZipCode,cName) VALUES ('9996','Fakturaservice');
INSERT INTO TCity (cZipCode,cName) VALUES ('9997','Fakturascanning');
INSERT INTO TCity (cZipCode,cName) VALUES ('9998','Borgerservice');
INSERT INTO TCity (cZipCode,cName) VALUES ('2412','Santa Claus/Julemanden');
INSERT INTO TCity (cZipCode,cName) VALUES ('3900','Nuuk');
INSERT INTO TCity (cZipCode,cName) VALUES ('3905','Nuussuaq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3910','Kangerlussuaq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3911','Sisimiut');
INSERT INTO TCity (cZipCode,cName) VALUES ('3912','Maniitsoq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3913','Tasiilaq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3915','Kulusuk');
INSERT INTO TCity (cZipCode,cName) VALUES ('3919','Alluitsup Paa');
INSERT INTO TCity (cZipCode,cName) VALUES ('3920','Qaqortoq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3921','Narsaq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3922','Nanortalik');
INSERT INTO TCity (cZipCode,cName) VALUES ('3923','Narsarsuaq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3924','Ikerasassuaq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3930','Kangilinnguit');
INSERT INTO TCity (cZipCode,cName) VALUES ('3932','Arsuk');
INSERT INTO TCity (cZipCode,cName) VALUES ('3940','Paamiut');
INSERT INTO TCity (cZipCode,cName) VALUES ('3950','Aasiaat');
INSERT INTO TCity (cZipCode,cName) VALUES ('3951','Qasigiannguit');
INSERT INTO TCity (cZipCode,cName) VALUES ('3952','Ilulissat');
INSERT INTO TCity (cZipCode,cName) VALUES ('3953','Qeqertarsuaq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3955','Kangaatsiaq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3961','Uummannaq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3962','Upernavik');
INSERT INTO TCity (cZipCode,cName) VALUES ('3964','Qaarsut');
INSERT INTO TCity (cZipCode,cName) VALUES ('3970','Pituffik');
INSERT INTO TCity (cZipCode,cName) VALUES ('3971','Qaanaaq');
INSERT INTO TCity (cZipCode,cName) VALUES ('3972','Station Nord');
INSERT INTO TCity (cZipCode,cName) VALUES ('3980','Ittoqqortoormiit');
INSERT INTO TCity (cZipCode,cName) VALUES ('3982','Mestersvig');
INSERT INTO TCity (cZipCode,cName) VALUES ('3984','Danmarkshavn');
INSERT INTO TCity (cZipCode,cName) VALUES ('3985','Constable Pynt');
INSERT INTO TCity (cZipCode,cName) VALUES ('3992','SlÊdepatrulje Sirius');